# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17FirDnJEwkJdBZK9WJ7yogEHthgBeieS
"""

import requests
from bs4 import BeautifulSoup as BS

r = requests.get("http://www.stu.ru/news/index.php")
html = BS(r.content, "html.parser")

items = html.select("#page_text > div > .news_block_table_inner_page")

for el in items:
  title = el.select(".news_inner_text > b > span")
  print(title[0].text)

for el in items:
  text= el.select(".news_inner_text > span")
  print(text[0].text)

for el in items:
  date = el.select(".news_block_date > span")
  print(date[0].text)

for el in items:
  month = el.select(".month_year")
  print(month[0].text)

