# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yIIN0PbQiYTGq9hWLiSbrINPDS9AoO7P
"""

import requests
from bs4 import BeautifulSoup as BS

r = requests.get("https://printcollege.ru/news")
html = BS(r.content, "html.parser")

items = html.select("#main > .twocoloms > .content-frame > .content >.content-holder")

for el in items:
  title = el.select("p")
  for i in title:
    print(i.text )

for el in items:
    text = el.select('.item')
    for i in text:
        for el in i.find_all():
            if el.name not in ['small', 'p', 'br', 'b', 'a']:
                print(el.text)

for el in items:
  date = el.select("small")
  for i in date:
    print(i.text )